config/routes.rb
Rails.application.routes.draw do

  resources :categories
  get "signin" => "sessions#new"
  resource :session

  get "signup" => "users#new"
    resources :users

    root "events#index"

    get 'events/filter/:scope' => "events#index", as: :filtered_events

    resources:events do
      resources :registrations
      resources :likes
    end
  end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :slug, uniqueness: true
  validates :location, presence: true
  validates :description, length: { minimum: 25 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :image_file_name, allow_blank: true, format: {
    with:    /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  before_validation :generate_slug

  scope :upcoming, -> { where('starts_at >= ?', Time.now).order(:starts_at) }
  scope :past, -> { where('starts_at < ?', Time.now).order(:starts_at) }
  scope :free, -> { upcoming.where(price: 0.0).order(:name) }
  scope :recent, ->(max=3) { past.limit(max) }

  def free?
    price.blank? || price.zero?
  end

  def spots_left
    if capacity.zero?
      0
    else
      capacity - registrations.size
    end
  end

  def sold_out?
    spots_left.zero?
  end

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize if name
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :require_signin, except: [:index, :show]
before_action :require_admin, except: [:index, :show]
before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    case params[:scope]
    when "past"
      @events = Event.past
    when "free"
      @events = Event.free
    when "recent"
      @events = Event.recent
    else
      @events = Event.upcoming
    end
  end

  def show
    @likers = @event.likers


    if current_user
    @current_like = current_user.likes.find_by(event_id: @event.id)
    end

    @categories = @event.categories
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event successfully updated!"
    else
      render :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "Event successfully created!"
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, alert: "Event successfully deleted!"
  end

private
  def set_event
    @event = Event.find_by!(slug: params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity, category_ids: [])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, 'Free')
    else
      number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag event.image_file_name
    end
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<%= render 'shared/errors', object: @event %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :location %>
        <%= f.text_field :location, size: 30 %>
      </li>
      <li class="required">
        <%= f.label :price %>
        <%= f.number_field :price, size: 6 %>
      </li>
      <li class="required">
        <%= f.label :starts_at %>
        <%= f.datetime_select :starts_at %>
      </li>
      <li class="required">
        <%= f.label :capacity %>
        <%= f.number_field :capacity, size: 6 %>
      </li>
      <li class="required">
        <%= f.label :image_file_name, 'Image Filename' %>
        <%= f.text_field :image_file_name, size: 30,
                         placeholder: "GIF, JPG, or PNG file name" %>
      </li>
      <li>
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", events_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/events/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @event.name %></h1>
</header>

<%= render 'form' %>

app/views/events/index.html.erb
<ul id="events">
  <% @events.each do |event| %>
    <li>
      <article class="event">
        <header>
          <%= image_for(event) %>
          <h2><%= link_to(event.name, event) %></h2>
          <h3><%= pluralize(event.spots_left, 'spot') %> available</h3>
        </header>
        <p>
          <%= truncate(event.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>When</th>
            <td><%= event.starts_at %></td>
          </tr>
          <tr>
            <th>Where</th>
            <td><%= event.location %></td>
          </tr>
          <tr>
            <th>Price</th>
            <td><%= format_price(event) %></td>
          </tr>
        </table>
      </article>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<header id="content-header">
  <h1>Add New Event</h1>
</header>

<%= render 'form' %>

app/views/events/show.html.erb
<% title(@event.name) %>
<article id="event" class="event">
  <header>
    <%= image_for(@event) %>
    <h1><%= @event.name %></h1>
    <h2><%= @event.starts_at %></h2>
  </header>

  <p>
    <%= @event.description %>
  </p>
  <p>
    <%= pluralize(@likers.size, 'like') %>
  </p>
  <% if current_user %>
    <% if @current_like %>
      <%= button_to "Unlike", event_like_path(@event, @current_like), method: :delete %>
    <% else %>
      <%= button_to "Like", event_likes_path(@event) %>
    <% end %>
  <% end %>

  <% content_for(:side) do %>
  <% if @likers.any? %>
    <h3>Likers</h3>
    <ul>
      <% @likers.each do |user| %>
      <li>
        <%= link_to user.name, user %>
      </li>
      <% end %>
    </ul>
  <% end %>



  <h3>Categories</h3>
  <ul>
    <% @categories.each do |category| %>
    <li><%= category.name %></li>
    <% end %>
  </ul>
  <% end %>

  <h3>Price</h3>
  <p>
    <%= format_price(@event) %>
  </p>

  <h3>Location</h3>
  <p>
    <%= @event.location %>
  </p>

  <h3>Capacity</h3>
  <p>
    <%= pluralize(@event.capacity, 'spot') %>
  </p>


  <%= link_to "Who's Registered?", event_registrations_path(@event) %>

  <footer>
    <%= register_link(@event) %>
      <p>
        (<%= pluralize(@event.spots_left, 'spot') %> available)
      </p>
    <nav>
      <% if current_user_admin? %>
      <%= link_to 'Edit', edit_event_path(@event), class: 'button' %>
      <%= link_to 'Delete', @event,
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </nav>
  </footer>
</article>