config/routes.rb
Rails.application.routes.draw do

  resources :categories
  get "signin" => "sessions#new"
  resource :session

  get "signup" => "users#new"
    resources :users

    root "events#index"

    get 'events/filter/:scope' => "events#index", as: :filtered_events

    resources:events do
      resources :registrations
      resources :likes
    end
  end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2015
    <%= link_to 'Stefan Sanchez','http://stefansanchez.com' %><br />
    Educational Tutorial from the Pragmatic Studio.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Events', root_path %></h1>
    <nav>
      <p>
        <% if current_user %>
          <%= link_to current_user.name, current_user %>
          <%= link_to "Account Settings", edit_user_path(current_user), class: 'button' %>
          <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
        <% else %>
          <%= link_to 'Sign Up', signup_path, class: 'button' %>
          <%= link_to 'Sign In', signin_path, class: 'button' %>
        <% end %>
      </p>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="events">
        <%= link_to "Upcoming", events_path, class: 'button' %>
      </li>
      <li class="events">
        <%= link_to "Past", filtered_events_path(:past), class: 'button' %>
      </li>
      <li class="events">
        <%= link_to "Free", filtered_events_path(:free), class: 'button' %>
      <li class="events">
        <%= link_to "Recent", filtered_events_path(:recent), class: 'button' %>
      </li>
      <% if current_user_admin? %>
      <li class="create-event">
        <%= link_to "Add New Event", new_event_path, class: 'button' %>
      </li>
      <% end %>
    </ul>
  </nav>
  <%= content_for(:side) %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div id="wrapper">
  <p>
    <%= render 'layouts/flashes' %>
  </p>
  <div id="container">
    <%= render "layouts/sidebar" %>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render 'layouts/footer' %>

</body>
</html>